#include "pt_util.h"

int pt_failures = 0;
int pt_checks = 0;

void test_log(void);
void test_pe(void);
void test_pe_loader(void);
void test_zip(void);
void test_cpu(void);
void test_gfx_audio(void);
void test_host(void);
void test_vfs(void);
void test_win32(void);
void test_surf(void);
void test_vm(void);
void test_peproc(void);
void test_wincompat(void);
void test_cpu64(void);
void test_visual(void);
void test_win32x(void);
void test_dll(void);
void test_pes(void);
void test_cpu64ext(void);
void test_pe_real(void);
void test_unwind(void);
void test_cpuid(void);
void test_input(void);
void test_gl(void);
void test_gl2(void);
void test_gl3(void);
void test_gl4(void);
void test_gl5(void);
void test_gl6(void);
void test_gl7(void);
void test_gl8(void);
void test_gl9(void);
void test_gl10(void);
void test_gl11(void);
void test_gdiwin(void);

int main(void) {
    printf("== PorticoRuntime: testes C ==\n");
    RUN(test_log);
    RUN(test_pe);
    RUN(test_pe_loader);
    RUN(test_zip);
    RUN(test_cpu);
    RUN(test_gfx_audio);
    RUN(test_host);
    RUN(test_vfs);
    RUN(test_win32);
    RUN(test_surf);
    RUN(test_vm);
    RUN(test_peproc);
    RUN(test_win32x);
    RUN(test_dll);
    RUN(test_pes);
    RUN(test_cpu64ext);
    RUN(test_pe_real);
    RUN(test_unwind);
    RUN(test_cpuid);
    RUN(test_input);
    RUN(test_gl);
    RUN(test_gl2);
    RUN(test_gl3);
    RUN(test_gl4);
    RUN(test_gl5);
    RUN(test_gl6);
    RUN(test_gl7);
    RUN(test_gl8);
    RUN(test_gl9);
    RUN(test_gl10);
    RUN(test_gl11);
    RUN(test_gdiwin);
    RUN(test_wincompat);
    RUN(test_cpu64);
    RUN(test_visual);
    printf("\n%d verificações, %d falhas\n", pt_checks, pt_failures);
    return pt_failures ? 1 : 0;
}
